find_paths:
  LLVM_CONFIG_BINARY:
    kind: Executable
    optional: false
    try:
      - llvm-config
    version:
      min: "4"
      max: "6"
      variable: LLVM_VERSION
      command: "% --version"
      regex: "^([0-9]+)."
    error_message: Failed to find llvm version
  LLVM_DIR:
    kind: Directory
    optional: false
    list: false
    try:
      - shell: "{LLVM_CONFIG_BINARY} --ldflags"
        regex: "-L([^ ]+)/lib"
        multiple: false
  LLVM_INCLUDES:
    kind: Directory
    optional: false
    list:
      separator: " -I"
      template: "%"
    try:
      - "{LLVM_DIR}/include/c++/v1"
      - "{LLVM_DIR}/lib/clang/*/include"
  CLANG_BINARY:
    kind: Executable
    optional: false
    search_paths:
      - "{LLVM_DIR}"
    try:
      - "bin/clang++"
    version:
      min: "4"
      max: "6"
      variable: CLANG_VERSION
      command: "% --version"
      regex: "^clang version ([0-9]+)."
