"^(MAX_TOUCH_POINTS|MAX_SHADER_LOCATIONS|MAX_MATERIAL_MAPS)$":
  map_as: Constant
  flags: false
  destination: "::"
# "^(LIGHTGRAY|GRAY|DARKGRAY|YELLOW|GOLD|ORANGE|PINK|RED|MAROON|GREEN|LIME|DARKGREEN|SKYBLUE|BLUE|DARKBLUE|PURPLE|VIOLET|DARKPURPLE|BEIGE|BROWN|DARKBROWN|WHITE|BLACK|BLANK|MAGENTA|RAYWHITE)$":
# LIGHTGRAY:
#   map_as: Constant
#   destination: "Enum::Colors"
#   type: Color
