"char *":
  builtin: true
  crystal_type: "String"
"void (int, const char *, __va_list_tag *)": { ignore: true }
"void ()": { ignore: true }
"void (void *)": { ignore: true }
"unsigned int [7]":
  builtin: true
  crystal_type: "LibC::UInt[7]"
"unsigned int [2]":
  builtin: true
  crystal_type: "LibC::UInt[2]"
"float [4]":
  builtin: true
  crystal_type: "LibC::Float[4]"
"int [32]":
  builtin: true
  crystal_type: "LibC::Int[32]"
"char [32]":
  builtin: true
  crystal_type: "LibC::Char[32]"