classes:
  Color: Color
  Vector2: Vector2
  Vector3: Vector3
  Vector4: Vector4
  Matrix: Matrix
  Rectangle: Rectangle
  Image: Image
  Texture: Texture
  RenderTexture: RenderTexture
  NPatchInfo: NPatchInfo
  CharInfo: CharInfo
  Font: Font
  SpriteFont: SpriteFont
  Camera3D: Camera3D
  Camera2D: Camera2D
  Mesh: Mesh
  Shader: Shader
  MaterialMap: MaterialMap
  Material: Material
  Transform: Transform
  BoneInfo: BoneInfo
  Model: Model
  ModelAnimation: ModelAnimation
  Ray: Ray
  RayHitInfo: RayHitInfo
  BoundingBox: BoundingBox
  Wave: Wave
  Sound: Sound
  AudioStream: AudioStream
  VrDeviceInfo: VrDeviceInfo
